name: Run R Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'  # Specify the R version you need
    
    - name: Set up pandoc
      uses: r-lib/actions/setup-pandoc@v2
      
    - name: Set up renv
      uses: r-lib/actions/setup-renv@v2

    - name: Run run.R to generate new report
      run: |
        Rscript run.R
    
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit changes
      run: |
        git add .
        git commit -m 'Add new report'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}